monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

    handlers:
        main:
            action_level: 'warning'
            buffer_size: 50
            excluded_http_codes: [400, 401, 403, 404, 405]
            handler: 'nested'
            type: 'fingers_crossed'

        nested:
            channels: ['!event']
            level: 'info'
            max_files: 10
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            type: 'rotating_file'

when@dev:
    monolog:
        handlers:
            deprecation:
                channels: ['deprecation']
                level: 'info'
                max_files: 10
                path: '%kernel.logs_dir%/%kernel.environment%-deprecation.log'
                type: 'rotating_file'
